site_name: fptools documentation
site_url: 
repo_url: https://github.com/tischfieldlab/fptools

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.tracking
    # - toc.integrate
    - toc.follow
    # Tabs
    # - navigation.tabs
    # - navigation.tabs.sticky  # stays visible at the top
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    # Insiders:
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.instant.preview
    - content.code.select
    - content.footnote.tooltips

plugins:
  - search
  # - privacy  # Caching dynamic badges
  # - mkdocs-jupyter
  # - mike
  - autorefs
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
        - scripts/gen_changelog.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            summary: true
            show_root_heading: true
            docstring_options:
              returns_multiple_items: false
            docstring_section_style: list  # table, list, spacy


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
  - Overview: index.md
  - Examples: examples.md
  - Changelog: changelog.md
  - Releases: https://github.com/tischfieldlab/fptools/releases
  - Core API:
    - Data Loading: loading.md
    - Session: session.md
  #  - Formats: formats.md
  - Full API: reference/
